// Tests for: ModDocGenerator Tests
#include "test_log.h"
#include "components/core_components.h"
#include "ecs/component.h"
#include "ecs/system.h"
#include "systems/mod_doc_generator_system.h"

using namespace atlas;

// ==================== ModDocGenerator Tests ====================

static void testModDocCreate() {
    std::cout << "\n=== ModDocGenerator: Create ===" << std::endl;
    ecs::World world;
    systems::ModDocGeneratorSystem sys(&world);
    auto* e = world.createEntity("mdg1");
    assertTrue(sys.createGenerator("mdg1"), "Create generator succeeds");
    auto* mdg = e->getComponent<components::ModDocGenerator>();
    assertTrue(mdg != nullptr, "Component exists");
    assertTrue(mdg->active, "Active by default");
    assertTrue(mdg->title == "Nova Forge Modding Reference", "Default title");
    assertTrue(mdg->version == "1.0", "Default version");
    assertTrue(!mdg->generated, "Not generated by default");
}

static void testModDocRegister() {
    std::cout << "\n=== ModDocGenerator: Register ===" << std::endl;
    ecs::World world;
    systems::ModDocGeneratorSystem sys(&world);
    world.createEntity("mdg1");
    sys.createGenerator("mdg1");
    assertTrue(sys.registerType("mdg1", "BasicShip", "Ship", "A basic ship", 5), "Register succeeds");
    assertTrue(sys.getEntryCount("mdg1") == 1, "Entry count is 1");
}

static void testModDocDuplicate() {
    std::cout << "\n=== ModDocGenerator: Duplicate ===" << std::endl;
    ecs::World world;
    systems::ModDocGeneratorSystem sys(&world);
    world.createEntity("mdg1");
    sys.createGenerator("mdg1");
    assertTrue(sys.registerType("mdg1", "BasicShip", "Ship", "A basic ship", 5), "First register");
    assertTrue(!sys.registerType("mdg1", "BasicShip", "Ship", "Duplicate", 3), "Duplicate rejected");
    assertTrue(sys.getEntryCount("mdg1") == 1, "Still one entry");
}

static void testModDocAddExample() {
    std::cout << "\n=== ModDocGenerator: AddExample ===" << std::endl;
    ecs::World world;
    systems::ModDocGeneratorSystem sys(&world);
    auto* e = world.createEntity("mdg1");
    sys.createGenerator("mdg1");
    sys.registerType("mdg1", "BasicShip", "Ship", "A basic ship", 5);
    assertTrue(sys.addExample("mdg1", "BasicShip"), "Add example succeeds");
    auto* mdg = e->getComponent<components::ModDocGenerator>();
    assertTrue(mdg->entries[0].has_example, "Example flag set");
    assertTrue(!sys.addExample("mdg1", "NonExistent"), "Add example to missing type fails");
}

static void testModDocValidate() {
    std::cout << "\n=== ModDocGenerator: Validate ===" << std::endl;
    ecs::World world;
    systems::ModDocGeneratorSystem sys(&world);
    world.createEntity("mdg1");
    sys.createGenerator("mdg1");
    sys.registerType("mdg1", "BasicShip", "Ship", "A basic ship", 5);
    sys.addExample("mdg1", "BasicShip");
    assertTrue(sys.validateEntry("mdg1", "BasicShip"), "Validation succeeds");
    assertTrue(sys.getValidatedCount("mdg1") == 1, "Validated count is 1");
}

static void testModDocValidateFail() {
    std::cout << "\n=== ModDocGenerator: ValidateFail ===" << std::endl;
    ecs::World world;
    systems::ModDocGeneratorSystem sys(&world);
    world.createEntity("mdg1");
    sys.createGenerator("mdg1");
    sys.registerType("mdg1", "BasicShip", "Ship", "A basic ship", 5);
    assertTrue(!sys.validateEntry("mdg1", "BasicShip"), "Validate without example fails");
    assertTrue(sys.getValidatedCount("mdg1") == 0, "Validated count still 0");
}

static void testModDocGenerate() {
    std::cout << "\n=== ModDocGenerator: Generate ===" << std::endl;
    ecs::World world;
    systems::ModDocGeneratorSystem sys(&world);
    world.createEntity("mdg1");
    sys.createGenerator("mdg1");
    sys.registerType("mdg1", "BasicShip", "Ship", "A basic ship", 5);
    sys.addExample("mdg1", "BasicShip");
    sys.validateEntry("mdg1", "BasicShip");
    assertTrue(sys.generate("mdg1"), "Generate succeeds");
    assertTrue(sys.isGenerated("mdg1"), "Is generated");
    assertTrue(sys.getGenerationCount("mdg1") == 1, "Generation count is 1");
}

static void testModDocGenerateFail() {
    std::cout << "\n=== ModDocGenerator: GenerateFail ===" << std::endl;
    ecs::World world;
    systems::ModDocGeneratorSystem sys(&world);
    world.createEntity("mdg1");
    sys.createGenerator("mdg1");
    sys.registerType("mdg1", "BasicShip", "Ship", "A basic ship", 5);
    assertTrue(!sys.generate("mdg1"), "Generate fails with unvalidated entries");
    assertTrue(!sys.isGenerated("mdg1"), "Not generated");
}

static void testModDocCategory() {
    std::cout << "\n=== ModDocGenerator: Category ===" << std::endl;
    ecs::World world;
    systems::ModDocGeneratorSystem sys(&world);
    world.createEntity("mdg1");
    sys.createGenerator("mdg1");
    sys.registerType("mdg1", "BasicShip", "Ship", "A ship", 5);
    sys.registerType("mdg1", "LaserModule", "Module", "A module", 3);
    sys.registerType("mdg1", "HeavyShip", "Ship", "Heavy ship", 8);
    assertTrue(sys.getEntriesByCategory("mdg1", "Ship") == 2, "Two ship entries");
    assertTrue(sys.getEntriesByCategory("mdg1", "Module") == 1, "One module entry");
    assertTrue(sys.getEntriesByCategory("mdg1", "Mission") == 0, "Zero mission entries");
}

static void testModDocMissing() {
    std::cout << "\n=== ModDocGenerator: Missing ===" << std::endl;
    ecs::World world;
    systems::ModDocGeneratorSystem sys(&world);
    assertTrue(!sys.createGenerator("nonexistent"), "Create fails on missing");
    assertTrue(!sys.registerType("nonexistent", "X", "Ship", "desc", 1), "Register fails on missing");
    assertTrue(!sys.addExample("nonexistent", "X"), "AddExample fails on missing");
    assertTrue(!sys.validateEntry("nonexistent", "X"), "Validate fails on missing");
    assertTrue(!sys.generate("nonexistent"), "Generate fails on missing");
    assertTrue(sys.getEntryCount("nonexistent") == 0, "0 entries on missing");
    assertTrue(!sys.isGenerated("nonexistent"), "Not generated on missing");
    assertTrue(sys.getValidatedCount("nonexistent") == 0, "0 validated on missing");
    assertTrue(sys.getGenerationCount("nonexistent") == 0, "0 generations on missing");
}


void run_mod_doc_generator_tests() {
    testModDocCreate();
    testModDocRegister();
    testModDocDuplicate();
    testModDocAddExample();
    testModDocValidate();
    testModDocValidateFail();
    testModDocGenerate();
    testModDocGenerateFail();
    testModDocCategory();
    testModDocMissing();
}
