/**
 * Test runner for Nova Forge C++ server system tests.
 * Auto-generated from the monolithic test_systems.cpp split.
 */
#include <iostream>

// Global test counters
int testsRun = 0;
int testsPassed = 0;

// Forward declarations of per-file registration functions
void run_capacitor_system_tests();
void run_shield_recharge_system_tests();
void run_single_component_system_tests();
void run_state_machine_system_tests();
void run_recharge_system_tests();
void run_weapon_system_tests();
void run_targeting_system_tests();
void run_ship_database_tests();
void run_wormhole_database_tests();
void run_wormhole_system_tests();
void run_fleet_system_tests();
void run_world_persistence_tests();
void run_movement_system_tests();
void run_logger_tests();
void run_server_metrics_tests();
void run_mission_system_tests();
void run_skill_system_tests();
void run_module_system_tests();
void run_inventory_system_tests();
void run_loot_system_tests();
void run_npc_database_tests();
void run_drone_system_tests();
void run_insurance_system_tests();
void run_bounty_system_tests();
void run_market_system_tests();
void run_corporation_system_tests();
void run_contract_system_tests();
void run_persistence_tests();
void run_pisystem_tests();
void run_manufacturing_system_tests();
void run_research_system_tests();
void run_chat_system_tests();
void run_character_creation_system_tests();
void run_tournament_system_tests();
void run_leaderboard_system_tests();
void run_station_system_tests();
void run_wreck_salvage_system_tests();
void run_server_console_tests();
void run_fleet_morale_system_tests();
void run_captain_personality_system_tests();
void run_fleet_chatter_system_tests();
void run_warp_anomaly_system_tests();
void run_captain_relationship_system_tests();
void run_emotional_arc_system_tests();
void run_fleet_cargo_system_tests();
void run_tactical_overlay_system_tests();
void run_combat_system_tests();
void run_ai_system_tests();
void run_warp_system_tests();
void run_mining_system_tests();
void run_ecs_components_tests();
void run_protocol_handler_tests();
void run_refining_system_tests();
void run_pcg_ship_generator_tests();
void run_fleet_formation_system_tests();
void run_captain_memory_system_tests();
void run_ship_fitting_system_tests();
void run_warp_cinematic_system_tests();
void run_anomaly_system_tests();
void run_scanner_system_tests();
void run_difficulty_scaling_system_tests();
void run_mission_template_system_tests();
void run_mission_generator_system_tests();
void run_reputation_system_tests();
void run_lod_system_tests();
void run_stress_test_tests();
void run_economy_tests();
void run_fleet_chatter_tests();
void run_captain_relationship_tests();
void run_rumor_propagation_tests();
void run_captain_personality_tests();
void run_persistence_stress_tests();
void run_spatial_hash_system_tests();
void run_compressed_persistence_tests();
void run_background_simulation_system_tests();
void run_npc_intent_system_tests();
void run_npc_behavior_tree_system_tests();
void run_combat_threat_system_tests();
void run_security_response_system_tests();
void run_ambient_traffic_system_tests();
void run_snapshot_replication_system_tests();
void run_interest_management_system_tests();
void run_pcg_framework_tests();
void run_character_mesh_cybernetics_tests();
void run_asteroid_field_generator_tests();
void run_anomaly_generator_tests();
void run_npc_encounter_generator_tests();
void run_warp_hudtravel_mode_tests();
void run_warp_auto_comfort_tests();
void run_warp_accessibility_tunnel_geometry_tests();
void run_phase_11_fleet_progression_system_tests();
void run_phase_11_fleet_cargo_ship_loss_tests();
void run_phase_11_station_deployment_system_tests();
void run_phase_11_fleet_warp_formation_system_tests();
void run_phase_11_fleet_civilization_tests();
void run_warp_meditation_system_tests();
void run_rumor_questline_system_tests();
void run_captain_departure_system_tests();
void run_captain_transfer_system_tests();
void run_npc_rerouting_system_tests();
void run_local_reputation_system_tests();
void run_station_news_system_tests();
void run_wreck_persistence_system_tests();
void run_fleet_history_system_tests();
void run_character_mesh_system_tests();
void run_rig_system_tests();
void run_turret_generator_tests();
void run_planet_generator_tests();
void run_habitat_generator_tests();
void run_grav_bike_tests();
void run_legend_system_tests();
void run_ancient_tech_tests();
void run_docking_system_tests();
void run_survival_system_tests();
void run_menu_system_tests();
void run_crew_system_tests();
void run_salvage_exploration_tests();
void run_interior_exterior_coupling_tests();
void run_race_and_lore_tests();
void run_market_order_tests();
void run_spine_hull_generator_tests();
void run_terrain_generator_tests();
void run_turret_placement_system_tests();
void run_damage_state_generator_tests();
void run_procedural_texture_generator_tests();
void run_economy_driven_generator_tests();
void run_ai_economic_actor_system_tests();
void run_turret_ai_system_tests();
void run_expanded_ship_class_tests();
void run_star_system_generator_tests();
void run_galaxy_generator_tests();
void run_alliance_system_tests();
void run_sovereignty_system_tests();
void run_war_declaration_system_tests();
void run_convoy_ambush_system_tests();
void run_npc_dialogue_system_tests();
void run_station_monument_system_tests();
void run_information_propagation_system_tests();
void run_crew_activity_system_tests();
void run_visual_cue_system_tests();
void run_black_market_system_tests();
void run_price_history_system_tests();
void run_propaganda_system_tests();
void run_rest_station_system_tests();
void run_myth_boss_system_tests();
void run_ancient_tech_upgrade_system_tests();
void run_mod_manifest_system_tests();
void run_ancient_ai_remnant_system_tests();
void run_character_creation_screen_system_tests();
void run_view_mode_transition_system_tests();
void run_station_hangar_system_tests();
void run_tether_docking_system_tests();
void run_fps_spawn_system_tests();
void run_fps_character_controller_system_tests();
void run_interior_door_system_tests();
void run_eva_airlock_system_tests();
void run_fps_interaction_system_tests();
void run_fps_combat_system_tests();
void run_fps_inventory_system_tests();
void run_ship_interior_layout_system_tests();
void run_environmental_hazard_system_tests();
void run_fpsobjective_system_tests();
void run_wing_management_system_tests();
void run_economic_flow_system_tests();
void run_resource_production_chain_system_tests();
void run_fleet_doctrine_system_tests();
void run_player_progression_system_tests();
void run_terraforming_system_tests();
void run_food_processor_system_tests();
void run_fleet_squad_system_tests();
void run_cloaking_system_tests();
void run_jump_drive_system_tests();
void run_cargo_scan_system_tests();
void run_commander_disagreement_system_tests();
void run_imperfect_information_system_tests();
void run_captain_background_system_tests();
void run_rover_interior_system_tests();
void run_bike_garage_system_tests();
void run_visual_rig_system_tests();
void run_planetary_traversal_system_tests();
void run_solar_panel_system_tests();
void run_farming_deck_system_tests();
void run_docking_ring_extension_system_tests();
void run_rover_bay_ramp_system_tests();
void run_grid_construction_system_tests();
void run_misc_tests();
void run_dock_node_layout_tests();
void run_mission_consequence_tests();
void run_server_performance_monitor_tests();
void run_atlas_uipanel_tests();
void run_keyboard_navigation_tests();
void run_data_binding_tests();
void run_entity_stress_test_tests();
void run_rig_locker_tests();
void run_visual_coupling_tests();
void run_fpssalvage_path_tests();
void run_lavatory_interaction_tests();
void run_evaairlock_exit_tests();
void run_ancient_module_discovery_tests();
void run_client_prediction_system_tests();
void run_ship_template_mod_system_tests();
void run_database_persistence_system_tests();
void run_task_scheduler_system_tests();
void run_mod_manager_system_tests();
void run_ship_designer_system_tests();
void run_mission_editor_system_tests();
void run_content_validation_system_tests();
void run_cloud_deployment_config_system_tests();
void run_visual_feedback_queue_tests();
void run_mod_doc_generator_tests();
void run_community_content_repository_system_tests();
void run_pv_ptoggle_system_tests();
void run_dynamic_event_system_tests();
void run_fleet_morale_resolution_system_tests();
void run_persistence_delta_system_tests();
void run_outer_rim_logistics_distortion_system_tests();
void run_rumor_propagation_system_tests();
void run_galactic_response_curve_system_tests();
void run_ship_capability_rating_system_tests();
void run_module_cascading_failure_system_tests();
void run_navigation_bookmark_system_tests();
void run_fleet_supply_line_system_tests();
void run_crew_training_system_tests();
void run_asteroid_belt_system_tests();
void run_scan_probe_system_tests();
void run_autopilot_system_tests();
void run_jump_gate_system_tests();
void run_procedural_mission_generator_system_tests();
void run_incursion_system_tests();
void run_clone_bay_system_tests();
void run_loyalty_point_store_system_tests();
void run_contract_auction_system_tests();
void run_trade_route_analytics_system_tests();
void run_combat_log_system_tests();
void run_fleet_coordination_system_tests();
void run_npc_patrol_route_system_tests();
void run_mining_belt_populator_system_tests();
void run_station_service_registry_system_tests();
void run_npc_schedule_system_tests();
void run_jitter_buffer_system_tests();
void run_entity_lifecycle_system_tests();
void run_player_wallet_system_tests();
void run_cargo_manifest_system_tests();
void run_loadout_persistence_system_tests();
void run_mission_reward_system_tests();
void run_player_standing_system_tests();
void run_undock_sequence_system_tests();
void run_damage_notification_system_tests();
void run_loot_container_system_tests();
void run_system_map_system_tests();
void run_overview_filter_system_tests();
void run_fps_enemy_ai_system_tests();
void run_fps_stealth_system_tests();
void run_fps_companion_system_tests();
void run_fps_terminal_hack_system_tests();
void run_fps_cover_system_tests();
void run_star_system_manager_system_tests();
void run_wallet_transaction_system_tests();
void run_spatial_partition_system_tests();
void run_player_session_system_tests();
void run_save_game_system_tests();
void run_onboarding_system_tests();
void run_star_system_populator_system_tests();
void run_session_progression_system_tests();
void run_encounter_spawner_system_tests();
void run_objective_tracker_system_tests();
void run_event_notification_feed_system_tests();
void run_session_summary_system_tests();
void run_market_browser_system_tests();
void run_skill_queue_system_tests();
void run_ship_fitting_validation_system_tests();
void run_combat_after_action_system_tests();
void run_transit_planner_system_tests();
void run_fleet_readiness_system_tests();
void run_damage_application_system_tests();
void run_combat_engagement_system_tests();
void run_warp_disruption_system_tests();
void run_invulnerability_timer_system_tests();
void run_mining_laser_cycle_system_tests();
void run_entity_builder_tests();
void run_ore_processing_system_tests();
void run_station_repair_service_system_tests();
void run_combat_reward_system_tests();
void run_thermal_management_system_tests();
void run_aggro_table_system_tests();
void run_cargo_transfer_system_tests();
void run_bounty_collection_system_tests();
void run_module_power_grid_system_tests();
void run_anomaly_escalation_system_tests();
void run_ship_repair_cost_system_tests();
void run_system_traffic_monitor_system_tests();
void run_fleet_command_terminal_system_tests();
void run_insurance_claim_system_tests();
void run_safe_zone_system_tests();
void run_ore_compression_system_tests();
void run_crew_management_system_tests();
void run_ship_maintenance_system_tests();
void run_fuel_consumption_system_tests();
void run_beacon_navigation_system_tests();
void run_formation_flight_system_tests();
void run_asteroid_respawn_system_tests();
void run_bounty_payout_system_tests();
void run_npc_trader_scheduler_system_tests();
void run_npc_fleet_composition_system_tests();
void run_docking_request_system_tests();
void run_tractor_beam_system_tests();
void run_contract_board_system_tests();
void run_module_overheat_system_tests();
void run_asteroid_mining_laser_system_tests();
void run_asteroid_depletion_tracker_system_tests();
void run_system_security_response_system_tests();
void run_power_grid_management_system_tests();
void run_salvage_drone_system_tests();
void run_cargo_hold_management_system_tests();
void run_market_trade_execution_system_tests();
void run_ship_approach_orbit_system_tests();
void run_combat_loot_drop_system_tests();
void run_damage_resistance_profile_system_tests();
void run_npc_spawn_scheduler_system_tests();
void run_skill_training_system_tests();
void run_warp_charge_sequence_system_tests();
void run_player_progression_tracking_system_tests();
void run_sector_map_discovery_system_tests();
void run_ship_loadout_preset_system_tests();
void run_mining_yield_optimizer_system_tests();
void run_fleet_coordination_broadcast_system_tests();
void run_station_service_broker_system_tests();
void run_jump_gate_activation_system_tests();
void run_asteroid_scanner_system_tests();
void run_ship_insurance_payout_system_tests();
void run_turret_tracking_system_tests();
void run_colony_management_system_tests();
void run_fps_input_context_system_tests();
void run_encounter_balance_system_tests();
void run_network_quality_monitor_system_tests();
void run_loot_table_system_tests();
void run_resource_respawn_system_tests();
void run_hyperspace_routing_system_tests();
void run_player_hangar_inventory_system_tests();
void run_snapshot_replication_system2_tests();
void run_server_tick_metrics_system_tests();
void run_shield_harmonics_system_tests();
void run_trade_route_optimizer_system_tests();
void run_scan_probe_deployment_system_tests();
void run_docking_bay_allocation_system_tests();
void run_fleet_warp_coordinator_system_tests();
void run_mining_laser_system_tests();
void run_npc_behavior_scheduler_system_tests();
void run_capacitor_warfare_system_tests();
void run_signature_analysis_system_tests();
void run_overheat_management_system_tests();
void run_salvage_processing_system_tests();
void run_jump_fatigue_tracker_system_tests();
void run_fleet_hangar_system_tests();
void run_mission_consequence_system_tests();
void run_supply_demand_system_tests();
void run_market_order_system_tests();
void run_ancient_module_discovery_system_tests();
void run_eva_airlock_exit_system_tests();
void run_salvage_exploration_system_tests();
void run_warp_performance_budget_system_tests();
void run_session_persistence_system_tests();
void run_star_system_population_system_tests();
void run_dynamic_difficulty_system_tests();
void run_gameplay_loop_tracker_system_tests();
void run_chat_router_system_tests();
void run_editor_overlay_system_tests();
void run_hangar_transition_system_tests();
void run_control_mode_context_system_tests();
void run_construction_placement_system_tests();
void run_fleet_progression_system_tests();
void run_hangar_environment_system_tests();
void run_titan_assembly_system_tests();
void run_station_deployment_system_tests();
void run_hull_class_capability_system_tests();
void run_interest_management_priority_system_tests();
void run_pvp_toggle_system_tests();
void run_fps_objective_system_tests();
void run_fleet_positional_audio_system_tests();
void run_atlas_ui_panel_system_tests();
void run_warp_hud_travel_mode_system_tests();
void run_space_planet_transition_system_tests();
void run_fps_salvage_path_system_tests();
void run_ancient_tech_system_tests();
void run_data_binding_system_tests();
void run_fleet_warp_formation_system_tests();
void run_keyboard_navigation_system_tests();
void run_shield_arc_hud_system_tests();
void run_capacitor_hud_bar_system_tests();
void run_velocity_arc_hud_system_tests();
void run_alert_stack_hud_system_tests();
void run_damage_feedback_hud_system_tests();
void run_gate_gun_system_tests();
void run_aggression_switching_system_tests();
void run_officer_spawn_system_tests();
void run_anomaly_spawning_system_tests();
void run_relay_clone_system_tests();
void run_aegis_spawn_system_tests();
void run_sleeper_ai_system_tests();
void run_order_matching_system_tests();
void run_blueprint_research_system_tests();
void run_drifter_ai_system_tests();
void run_warp_bubble_system_tests();
void run_invention_system_tests();
void run_regional_market_system_tests();
void run_sleeper_cache_system_tests();
void run_incursion_system_tests();
void run_meta_level_system_tests();
void run_reaction_formula_system_tests();
void run_session_manager_system_tests();
void run_player_spawn_system_tests();
void run_d_scan_system_tests();
void run_kill_report_system_tests();
void run_respawn_selection_system_tests();
void run_tutorial_system_tests();
void run_trade_window_system_tests();
void run_damage_log_system_tests();
void run_loot_distribution_system_tests();
void run_abyssal_filament_system_tests();
void run_abyssal_weather_system_tests();
void run_abyssal_escalation_system_tests();
void run_mutaplasmid_system_tests();
void run_capital_component_system_tests();
void run_planet_scan_system_tests();
void run_pi_customs_system_tests();
void run_pi_system_tests();
void run_tech2_module_system_tests();
void run_market_api_system_tests();
void run_relay_clone_install_ui_system_tests();
void run_dock_node_layout_system_tests();
void run_entity_stress_test_system_tests();
void run_lavatory_interaction_system_tests();
void run_mod_doc_generator_system_tests();
void run_rig_locker_system_tests();
void run_server_performance_monitor_system_tests();
void run_visual_coupling_system_tests();
void run_visual_feedback_queue_system_tests();
void run_warp_auto_comfort_system_tests();
void run_combat_timer_system_tests();
void run_player_notification_queue_system_tests();
void run_fleet_after_action_report_system_tests();
void run_ecm_jamming_system_tests();
void run_sensor_dampening_system_tests();
void run_tracking_disruption_system_tests();
void run_ship_skin_system_tests();
void run_propulsion_module_system_tests();
void run_citadel_management_system_tests();
void run_character_portrait_system_tests();
void run_inertia_modifier_system_tests();
void run_alliance_management_system_tests();
void run_corporation_logo_system_tests();
void run_structure_skin_system_tests();
void run_skill_injector_system_tests();
void run_stasis_web_system_tests();
void run_asset_safety_system_tests();
void run_command_burst_system_tests();
void run_target_painter_system_tests();
void run_warp_scrambler_system_tests();
void run_remote_repair_system_tests();
void run_daily_quest_system_tests();
void run_market_watchlist_system_tests();
void run_player_session_stats_system_tests();
void run_achievement_system_tests();
void run_mining_ledger_system_tests();
void run_fleet_broadcast_system_tests();
void run_player_mode_system_tests();
void run_control_port_system_tests();
void run_slot_grid_system_tests();
void run_density_field_system_tests();
void run_interior_nav_graph_system_tests();
void run_drone_logistics_system_tests();
void run_module_capability_system_tests();
void run_rig_link_system_tests();
void run_repair_timer_system_tests();
void run_agent_mission_system_tests();
void run_corp_tax_ledger_system_tests();
void run_fighter_squadron_system_tests();
void run_moon_mining_scheduler_system_tests();
void run_bookmark_system_tests();
void run_hangar_system_tests();
void run_notification_system_tests();
void run_survey_scanner_system_tests();
void run_fuel_block_system_tests();
void run_jump_clone_system_tests();
void run_access_list_system_tests();
void run_skill_plan_system_tests();
void run_overview_system_tests();
void run_fitting_validation_system_tests();
void run_cargo_container_system_tests();
void run_directional_scan_system_tests();
void run_fleet_advertisement_system_tests();
void run_wallet_journal_system_tests();
void run_character_sheet_system_tests();
void run_mail_system_tests();
void run_medal_system_tests();
void run_structure_browser_system_tests();
void run_player_presence_system_tests();
void run_fleet_norm_system_tests();
void run_sector_tension_system_tests();
void run_captain_psychology_system_tests();
void run_officer_spawn_system_tests();
void run_insurance_contract_system_tests();
void run_chatter_interrupt_system_tests();
void run_faction_behavior_modifier_system_tests();
void run_sim_sensor_confidence_system_tests();
void run_operational_wear_system_tests();
void run_behavioral_reputation_system_tests();
void run_post_event_analysis_system_tests();
void run_space_scar_system_tests();
void run_system_event_system_tests();
void run_fleet_fracture_recovery_system_tests();
void run_fleet_engagement_rules_system_tests();
void run_captain_milestone_system_tests();
void run_galactic_news_system_tests();
void run_captain_social_graph_system_tests();
void run_fleet_cargo_aggregator_system_tests();
void run_fleet_departure_system_tests();
void run_faction_doctrine_system_tests();
void run_ambient_event_system_tests();
void run_captain_stress_system_tests();
void run_captain_mood_system_tests();
void run_fleet_recon_system_tests();
void run_titan_countermeasure_system_tests();
void run_captain_mentorship_system_tests();
void run_fleet_culture_system_tests();
void run_captain_ambition_system_tests();
void run_fleet_insignia_system_tests();
void run_captain_legacy_system_tests();
void run_fleet_rivalry_system_tests();

int main() {
    std::cout << "========================================" << std::endl;
    std::cout << "Nova Forge C++ Server System Tests" << std::endl;
    std::cout << "========================================" << std::endl;

    run_capacitor_system_tests();
    run_shield_recharge_system_tests();
    run_single_component_system_tests();
    run_state_machine_system_tests();
    run_recharge_system_tests();
    run_weapon_system_tests();
    run_targeting_system_tests();
    run_ship_database_tests();
    run_wormhole_database_tests();
    run_wormhole_system_tests();
    run_fleet_system_tests();
    run_world_persistence_tests();
    run_movement_system_tests();
    run_logger_tests();
    run_server_metrics_tests();
    run_mission_system_tests();
    run_skill_system_tests();
    run_module_system_tests();
    run_inventory_system_tests();
    run_loot_system_tests();
    run_npc_database_tests();
    run_drone_system_tests();
    run_insurance_system_tests();
    run_bounty_system_tests();
    run_market_system_tests();
    run_corporation_system_tests();
    run_contract_system_tests();
    run_persistence_tests();
    run_pisystem_tests();
    run_manufacturing_system_tests();
    run_research_system_tests();
    run_chat_system_tests();
    run_character_creation_system_tests();
    run_tournament_system_tests();
    run_leaderboard_system_tests();
    run_station_system_tests();
    run_wreck_salvage_system_tests();
    run_server_console_tests();
    run_fleet_morale_system_tests();
    run_captain_personality_system_tests();
    run_fleet_chatter_system_tests();
    run_warp_anomaly_system_tests();
    run_captain_relationship_system_tests();
    run_emotional_arc_system_tests();
    run_fleet_cargo_system_tests();
    run_tactical_overlay_system_tests();
    run_combat_system_tests();
    run_ai_system_tests();
    run_warp_system_tests();
    run_mining_system_tests();
    run_ecs_components_tests();
    run_protocol_handler_tests();
    run_refining_system_tests();
    run_pcg_ship_generator_tests();
    run_fleet_formation_system_tests();
    run_captain_memory_system_tests();
    run_ship_fitting_system_tests();
    run_warp_cinematic_system_tests();
    run_anomaly_system_tests();
    run_scanner_system_tests();
    run_difficulty_scaling_system_tests();
    run_mission_template_system_tests();
    run_mission_generator_system_tests();
    run_reputation_system_tests();
    run_lod_system_tests();
    run_stress_test_tests();
    run_economy_tests();
    run_fleet_chatter_tests();
    run_captain_relationship_tests();
    run_rumor_propagation_tests();
    run_captain_personality_tests();
    run_persistence_stress_tests();
    run_spatial_hash_system_tests();
    run_compressed_persistence_tests();
    run_background_simulation_system_tests();
    run_npc_intent_system_tests();
    run_npc_behavior_tree_system_tests();
    run_combat_threat_system_tests();
    run_security_response_system_tests();
    run_ambient_traffic_system_tests();
    run_snapshot_replication_system_tests();
    run_interest_management_system_tests();
    run_pcg_framework_tests();
    run_character_mesh_cybernetics_tests();
    run_asteroid_field_generator_tests();
    run_anomaly_generator_tests();
    run_npc_encounter_generator_tests();
    run_warp_hudtravel_mode_tests();
    run_warp_auto_comfort_tests();
    run_warp_accessibility_tunnel_geometry_tests();
    run_phase_11_fleet_progression_system_tests();
    run_phase_11_fleet_cargo_ship_loss_tests();
    run_phase_11_station_deployment_system_tests();
    run_phase_11_fleet_warp_formation_system_tests();
    run_phase_11_fleet_civilization_tests();
    run_warp_meditation_system_tests();
    run_rumor_questline_system_tests();
    run_captain_departure_system_tests();
    run_captain_transfer_system_tests();
    run_npc_rerouting_system_tests();
    run_local_reputation_system_tests();
    run_station_news_system_tests();
    run_wreck_persistence_system_tests();
    run_fleet_history_system_tests();
    run_character_mesh_system_tests();
    run_rig_system_tests();
    run_turret_generator_tests();
    run_planet_generator_tests();
    run_habitat_generator_tests();
    run_grav_bike_tests();
    run_legend_system_tests();
    run_ancient_tech_tests();
    run_docking_system_tests();
    run_survival_system_tests();
    run_menu_system_tests();
    run_crew_system_tests();
    run_salvage_exploration_tests();
    run_interior_exterior_coupling_tests();
    run_race_and_lore_tests();
    run_market_order_tests();
    run_spine_hull_generator_tests();
    run_terrain_generator_tests();
    run_turret_placement_system_tests();
    run_damage_state_generator_tests();
    run_procedural_texture_generator_tests();
    run_economy_driven_generator_tests();
    run_ai_economic_actor_system_tests();
    run_turret_ai_system_tests();
    run_expanded_ship_class_tests();
    run_star_system_generator_tests();
    run_galaxy_generator_tests();
    run_alliance_system_tests();
    run_sovereignty_system_tests();
    run_war_declaration_system_tests();
    run_convoy_ambush_system_tests();
    run_npc_dialogue_system_tests();
    run_station_monument_system_tests();
    run_information_propagation_system_tests();
    run_crew_activity_system_tests();
    run_visual_cue_system_tests();
    run_black_market_system_tests();
    run_price_history_system_tests();
    run_propaganda_system_tests();
    run_rest_station_system_tests();
    run_myth_boss_system_tests();
    run_ancient_tech_upgrade_system_tests();
    run_mod_manifest_system_tests();
    run_ancient_ai_remnant_system_tests();
    run_character_creation_screen_system_tests();
    run_view_mode_transition_system_tests();
    run_station_hangar_system_tests();
    run_tether_docking_system_tests();
    run_fps_spawn_system_tests();
    run_fps_character_controller_system_tests();
    run_interior_door_system_tests();
    run_eva_airlock_system_tests();
    run_fps_interaction_system_tests();
    run_fps_combat_system_tests();
    run_fps_inventory_system_tests();
    run_ship_interior_layout_system_tests();
    run_environmental_hazard_system_tests();
    run_fpsobjective_system_tests();
    run_wing_management_system_tests();
    run_economic_flow_system_tests();
    run_resource_production_chain_system_tests();
    run_fleet_doctrine_system_tests();
    run_player_progression_system_tests();
    run_terraforming_system_tests();
    run_food_processor_system_tests();
    run_fleet_squad_system_tests();
    run_cloaking_system_tests();
    run_jump_drive_system_tests();
    run_cargo_scan_system_tests();
    run_commander_disagreement_system_tests();
    run_imperfect_information_system_tests();
    run_captain_background_system_tests();
    run_rover_interior_system_tests();
    run_bike_garage_system_tests();
    run_visual_rig_system_tests();
    run_planetary_traversal_system_tests();
    run_solar_panel_system_tests();
    run_farming_deck_system_tests();
    run_docking_ring_extension_system_tests();
    run_rover_bay_ramp_system_tests();
    run_grid_construction_system_tests();
    run_misc_tests();
    run_dock_node_layout_tests();
    run_mission_consequence_tests();
    run_server_performance_monitor_tests();
    run_atlas_uipanel_tests();
    run_keyboard_navigation_tests();
    run_data_binding_tests();
    run_entity_stress_test_tests();
    run_rig_locker_tests();
    run_visual_coupling_tests();
    run_fpssalvage_path_tests();
    run_lavatory_interaction_tests();
    run_evaairlock_exit_tests();
    run_ancient_module_discovery_tests();
    run_client_prediction_system_tests();
    run_ship_template_mod_system_tests();
    run_database_persistence_system_tests();
    run_task_scheduler_system_tests();
    run_mod_manager_system_tests();
    run_ship_designer_system_tests();
    run_mission_editor_system_tests();
    run_content_validation_system_tests();
    run_cloud_deployment_config_system_tests();
    run_visual_feedback_queue_tests();
    run_mod_doc_generator_tests();
    run_community_content_repository_system_tests();
    run_pv_ptoggle_system_tests();
    run_dynamic_event_system_tests();
    run_fleet_morale_resolution_system_tests();
    run_persistence_delta_system_tests();
    run_outer_rim_logistics_distortion_system_tests();
    run_rumor_propagation_system_tests();
    run_galactic_response_curve_system_tests();
    run_ship_capability_rating_system_tests();
    run_module_cascading_failure_system_tests();
    run_navigation_bookmark_system_tests();
    run_fleet_supply_line_system_tests();
    run_crew_training_system_tests();
    run_asteroid_belt_system_tests();
    run_scan_probe_system_tests();
    run_autopilot_system_tests();
    run_jump_gate_system_tests();
    run_procedural_mission_generator_system_tests();
    run_incursion_system_tests();
    run_clone_bay_system_tests();
    run_loyalty_point_store_system_tests();
    run_contract_auction_system_tests();
    run_trade_route_analytics_system_tests();
    run_combat_log_system_tests();
    run_fleet_coordination_system_tests();
    run_npc_patrol_route_system_tests();
    run_mining_belt_populator_system_tests();
    run_station_service_registry_system_tests();
    run_npc_schedule_system_tests();
    run_jitter_buffer_system_tests();
    run_entity_lifecycle_system_tests();
    run_player_wallet_system_tests();
    run_cargo_manifest_system_tests();
    run_loadout_persistence_system_tests();
    run_mission_reward_system_tests();
    run_player_standing_system_tests();
    run_undock_sequence_system_tests();
    run_damage_notification_system_tests();
    run_loot_container_system_tests();
    run_system_map_system_tests();
    run_overview_filter_system_tests();
    run_fps_enemy_ai_system_tests();
    run_fps_stealth_system_tests();
    run_fps_companion_system_tests();
    run_fps_terminal_hack_system_tests();
    run_fps_cover_system_tests();
    run_star_system_manager_system_tests();
    run_wallet_transaction_system_tests();
    run_spatial_partition_system_tests();
    run_player_session_system_tests();
    run_save_game_system_tests();
    run_onboarding_system_tests();
    run_star_system_populator_system_tests();
    run_session_progression_system_tests();
    run_encounter_spawner_system_tests();
    run_objective_tracker_system_tests();
    run_event_notification_feed_system_tests();
    run_session_summary_system_tests();
    run_market_browser_system_tests();
    run_skill_queue_system_tests();
    run_ship_fitting_validation_system_tests();
    run_combat_after_action_system_tests();
    run_transit_planner_system_tests();
    run_fleet_readiness_system_tests();
    run_damage_application_system_tests();
    run_combat_engagement_system_tests();
    run_warp_disruption_system_tests();
    run_invulnerability_timer_system_tests();
    run_mining_laser_cycle_system_tests();
    run_entity_builder_tests();
    run_ore_processing_system_tests();
    run_station_repair_service_system_tests();
    run_combat_reward_system_tests();
    run_thermal_management_system_tests();
    run_aggro_table_system_tests();
    run_cargo_transfer_system_tests();
    run_bounty_collection_system_tests();
    run_module_power_grid_system_tests();
    run_anomaly_escalation_system_tests();
    run_ship_repair_cost_system_tests();
    run_system_traffic_monitor_system_tests();
    run_fleet_command_terminal_system_tests();
    run_insurance_claim_system_tests();
    run_safe_zone_system_tests();
    run_ore_compression_system_tests();
    run_crew_management_system_tests();
    run_ship_maintenance_system_tests();
    run_fuel_consumption_system_tests();
    run_beacon_navigation_system_tests();
    run_formation_flight_system_tests();
    run_asteroid_respawn_system_tests();
    run_bounty_payout_system_tests();
    run_npc_trader_scheduler_system_tests();
    run_npc_fleet_composition_system_tests();
    run_docking_request_system_tests();
    run_tractor_beam_system_tests();
    run_contract_board_system_tests();
    run_module_overheat_system_tests();
    run_asteroid_mining_laser_system_tests();
    run_asteroid_depletion_tracker_system_tests();
    run_system_security_response_system_tests();
    run_power_grid_management_system_tests();
    run_salvage_drone_system_tests();
    run_cargo_hold_management_system_tests();
    run_market_trade_execution_system_tests();
    run_ship_approach_orbit_system_tests();
    run_combat_loot_drop_system_tests();
    run_damage_resistance_profile_system_tests();
    run_npc_spawn_scheduler_system_tests();
    run_skill_training_system_tests();
    run_warp_charge_sequence_system_tests();
    run_player_progression_tracking_system_tests();
    run_sector_map_discovery_system_tests();
    run_ship_loadout_preset_system_tests();
    run_mining_yield_optimizer_system_tests();
    run_fleet_coordination_broadcast_system_tests();
    run_station_service_broker_system_tests();
    run_jump_gate_activation_system_tests();
    run_asteroid_scanner_system_tests();
    run_ship_insurance_payout_system_tests();
    run_turret_tracking_system_tests();
    run_colony_management_system_tests();
    run_fps_input_context_system_tests();
    run_encounter_balance_system_tests();
    run_network_quality_monitor_system_tests();
    run_loot_table_system_tests();
    run_resource_respawn_system_tests();
    run_hyperspace_routing_system_tests();
    run_player_hangar_inventory_system_tests();
    run_snapshot_replication_system2_tests();
    run_server_tick_metrics_system_tests();
    run_shield_harmonics_system_tests();
    run_trade_route_optimizer_system_tests();
    run_scan_probe_deployment_system_tests();
    run_docking_bay_allocation_system_tests();
    run_fleet_warp_coordinator_system_tests();
    run_mining_laser_system_tests();
    run_npc_behavior_scheduler_system_tests();
    run_capacitor_warfare_system_tests();
    run_signature_analysis_system_tests();
    run_overheat_management_system_tests();
    run_salvage_processing_system_tests();
    run_jump_fatigue_tracker_system_tests();
    run_fleet_hangar_system_tests();
    run_mission_consequence_system_tests();
    run_supply_demand_system_tests();
    run_market_order_system_tests();
    run_ancient_module_discovery_system_tests();
    run_eva_airlock_exit_system_tests();
    run_salvage_exploration_system_tests();
    run_warp_performance_budget_system_tests();
    run_session_persistence_system_tests();
    run_star_system_population_system_tests();
    run_dynamic_difficulty_system_tests();
    run_gameplay_loop_tracker_system_tests();
    run_chat_router_system_tests();
    run_editor_overlay_system_tests();
    run_hangar_transition_system_tests();
    run_control_mode_context_system_tests();
    run_construction_placement_system_tests();
    run_fleet_progression_system_tests();
    run_hangar_environment_system_tests();
    run_titan_assembly_system_tests();
    run_station_deployment_system_tests();
    run_hull_class_capability_system_tests();
    run_interest_management_priority_system_tests();
    run_pvp_toggle_system_tests();
    run_fps_objective_system_tests();
    run_fleet_positional_audio_system_tests();
    run_atlas_ui_panel_system_tests();
    run_warp_hud_travel_mode_system_tests();
    run_space_planet_transition_system_tests();
    run_fps_salvage_path_system_tests();
    run_ancient_tech_system_tests();
    run_data_binding_system_tests();
    run_fleet_warp_formation_system_tests();
    run_keyboard_navigation_system_tests();
    run_shield_arc_hud_system_tests();
    run_capacitor_hud_bar_system_tests();
    run_velocity_arc_hud_system_tests();
    run_alert_stack_hud_system_tests();
    run_damage_feedback_hud_system_tests();
    run_gate_gun_system_tests();
    run_aggression_switching_system_tests();
    run_officer_spawn_system_tests();
    run_anomaly_spawning_system_tests();
    run_relay_clone_system_tests();
    run_aegis_spawn_system_tests();
    run_sleeper_ai_system_tests();
    run_order_matching_system_tests();
    run_blueprint_research_system_tests();
    run_drifter_ai_system_tests();
    run_warp_bubble_system_tests();
    run_invention_system_tests();
    run_regional_market_system_tests();
    run_sleeper_cache_system_tests();
    run_incursion_system_tests();
    run_meta_level_system_tests();
    run_reaction_formula_system_tests();
    run_session_manager_system_tests();
    run_player_spawn_system_tests();
    run_d_scan_system_tests();
    run_kill_report_system_tests();
    run_respawn_selection_system_tests();
    run_tutorial_system_tests();
    run_trade_window_system_tests();
    run_damage_log_system_tests();
    run_loot_distribution_system_tests();
    run_abyssal_filament_system_tests();
    run_abyssal_weather_system_tests();
    run_abyssal_escalation_system_tests();
    run_mutaplasmid_system_tests();
    run_capital_component_system_tests();
    run_planet_scan_system_tests();
    run_pi_customs_system_tests();
    run_pi_system_tests();
    run_tech2_module_system_tests();
    run_market_api_system_tests();
    run_relay_clone_install_ui_system_tests();
    run_dock_node_layout_system_tests();
    run_entity_stress_test_system_tests();
    run_lavatory_interaction_system_tests();
    run_mod_doc_generator_system_tests();
    run_rig_locker_system_tests();
    run_server_performance_monitor_system_tests();
    run_visual_coupling_system_tests();
    run_visual_feedback_queue_system_tests();
    run_warp_auto_comfort_system_tests();
    run_combat_timer_system_tests();
    run_player_notification_queue_system_tests();
    run_fleet_after_action_report_system_tests();
    run_ecm_jamming_system_tests();
    run_sensor_dampening_system_tests();
    run_tracking_disruption_system_tests();
    run_ship_skin_system_tests();
    run_propulsion_module_system_tests();
    run_citadel_management_system_tests();
    run_character_portrait_system_tests();
    run_inertia_modifier_system_tests();
    run_alliance_management_system_tests();
    run_corporation_logo_system_tests();
    run_structure_skin_system_tests();
    run_skill_injector_system_tests();
    run_stasis_web_system_tests();
    run_asset_safety_system_tests();
    run_command_burst_system_tests();
    run_target_painter_system_tests();
    run_warp_scrambler_system_tests();
    run_remote_repair_system_tests();
    run_daily_quest_system_tests();
    run_market_watchlist_system_tests();
    run_player_session_stats_system_tests();
    run_achievement_system_tests();
    run_mining_ledger_system_tests();
    run_fleet_broadcast_system_tests();
    run_player_mode_system_tests();
    run_control_port_system_tests();
    run_slot_grid_system_tests();
    run_density_field_system_tests();
    run_interior_nav_graph_system_tests();
    run_drone_logistics_system_tests();
    run_module_capability_system_tests();
    run_rig_link_system_tests();
    run_repair_timer_system_tests();
    run_agent_mission_system_tests();
    run_corp_tax_ledger_system_tests();
    run_fighter_squadron_system_tests();
    run_moon_mining_scheduler_system_tests();
    run_bookmark_system_tests();
    run_hangar_system_tests();
    run_notification_system_tests();
    run_survey_scanner_system_tests();
    run_fuel_block_system_tests();
    run_jump_clone_system_tests();
    run_access_list_system_tests();
    run_skill_plan_system_tests();
    run_overview_system_tests();
    run_fitting_validation_system_tests();
    run_cargo_container_system_tests();
    run_directional_scan_system_tests();
    run_fleet_advertisement_system_tests();
    run_wallet_journal_system_tests();
    run_character_sheet_system_tests();
    run_mail_system_tests();
    run_medal_system_tests();
    run_structure_browser_system_tests();
    run_player_presence_system_tests();
    run_fleet_norm_system_tests();
    run_sector_tension_system_tests();
    run_captain_psychology_system_tests();
    run_officer_spawn_system_tests();
    run_insurance_contract_system_tests();
    run_chatter_interrupt_system_tests();
    run_faction_behavior_modifier_system_tests();
    run_sim_sensor_confidence_system_tests();
    run_operational_wear_system_tests();
    run_behavioral_reputation_system_tests();
    run_post_event_analysis_system_tests();
    run_space_scar_system_tests();
    run_system_event_system_tests();
    run_fleet_fracture_recovery_system_tests();
    run_fleet_engagement_rules_system_tests();
    run_captain_milestone_system_tests();
    run_galactic_news_system_tests();
    run_fleet_cargo_aggregator_system_tests();
    run_captain_social_graph_system_tests();
    run_fleet_departure_system_tests();
    run_faction_doctrine_system_tests();
    run_ambient_event_system_tests();
    run_captain_stress_system_tests();
    run_captain_mood_system_tests();
    run_fleet_recon_system_tests();
    run_titan_countermeasure_system_tests();
    run_captain_mentorship_system_tests();
    run_fleet_culture_system_tests();
    run_captain_ambition_system_tests();
    run_fleet_insignia_system_tests();
    run_captain_legacy_system_tests();
    run_fleet_rivalry_system_tests();

    std::cout << "\n========================================" << std::endl;
    std::cout << "Results: " << testsPassed << "/" << testsRun << " tests passed" << std::endl;
    std::cout << "========================================" << std::endl;

    return (testsPassed == testsRun) ? 0 : 1;
}
