"""
Versioning — semver management, changelog generation, and build numbering.

Reads/writes a VERSION file, bumps semver levels, creates git tags,
writes C++ version headers, and generates changelogs from git log.
"""

import re
import subprocess
from pathlib import Path


class VersionManager:
    """Semver version management and release tooling."""

    # ------------------------------------------------------------------
    def get_current_version(self, version_file=None):
        """Read version from VERSION file or fall back to latest git tag."""
        if version_file and Path(version_file).exists():
            return Path(version_file).read_text().strip()
        try:
            r = subprocess.run(
                ["git", "describe", "--tags", "--abbrev=0"],
                capture_output=True, text=True
            )
            if r.returncode == 0:
                return r.stdout.strip().lstrip("v")
        except Exception:
            pass
        return "0.1.0"

    def bump_version(self, level="patch", version_file=None):
        """Increment major/minor/patch and write back to version_file."""
        ver = self.get_current_version(version_file)
        parts = ver.split(".")
        if len(parts) != 3:
            parts = ["0", "1", "0"]
        major, minor, patch = int(parts[0]), int(parts[1]), int(parts[2])
        if level == "major":
            major += 1; minor = 0; patch = 0
        elif level == "minor":
            minor += 1; patch = 0
        else:
            patch += 1
        new_ver = f"{major}.{minor}.{patch}"
        if version_file:
            Path(version_file).write_text(new_ver + "\n", encoding="utf-8")
        print(f"[VersionManager] bumped {ver} → {new_ver} ({level})")
        return new_ver

    def create_git_tag(self, version, message=""):
        """Create an annotated git tag for the given version."""
        tag = f"v{version}"
        msg = message or f"Release {tag}"
        try:
            subprocess.run(["git", "tag", "-a", tag, "-m", msg], check=True)
            print(f"[VersionManager] created tag {tag}")
        except Exception as e:
            print(f"[VersionManager] tag failed: {e}")
        return tag

    def write_version_header(self, version, output_path):
        """Write a C++ version header with #define macros."""
        parts = version.split(".")
        major = parts[0] if len(parts) > 0 else "0"
        minor = parts[1] if len(parts) > 1 else "0"
        patch = parts[2] if len(parts) > 2 else "0"
        header = (
            f"#pragma once\n"
            f"// Auto-generated by VersionManager — do not edit manually\n"
            f"#define NOVAFORGE_VERSION_MAJOR {major}\n"
            f"#define NOVAFORGE_VERSION_MINOR {minor}\n"
            f"#define NOVAFORGE_VERSION_PATCH {patch}\n"
            f'#define NOVAFORGE_VERSION_STRING "{version}"\n'
        )
        Path(output_path).write_text(header, encoding="utf-8")
        print(f"[VersionManager] wrote version header → {output_path}")
        return output_path

    def get_build_number(self):
        """Return the total git commit count as build number."""
        try:
            r = subprocess.run(
                ["git", "rev-list", "--count", "HEAD"],
                capture_output=True, text=True
            )
            if r.returncode == 0:
                return int(r.stdout.strip())
        except Exception:
            pass
        return 0

    def generate_changelog(self, since_version=None):
        """Generate a markdown changelog from git log."""
        cmd = ["git", "log", "--oneline", "--no-merges"]
        if since_version:
            cmd += [f"v{since_version}..HEAD"]
        try:
            r = subprocess.run(cmd, capture_output=True, text=True)
            if r.returncode != 0:
                return "# Changelog\n\n_No git history available._\n"
            lines = r.stdout.strip().splitlines()
            items = "\n".join(f"- {l}" for l in lines)
            return f"# Changelog\n\n{items}\n"
        except Exception:
            return "# Changelog\n\n_Error reading git log._\n"
